//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMDWebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DualDatabaseTestSchemeQuestion
    {
        public int ID { get; set; }
        public int GroupingId { get; set; }
        public string QuestionDescription { get; set; }
        public string MultipleChoiceCorrect { get; set; }
        public string MultipleChoiceB { get; set; }
        public string MultipleChoiceC { get; set; }
        public string MultipleChoiceD { get; set; }
        public string Answerexplanation { get; set; }
    }
}
