//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMDWebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DualDatabaseTestSchemeTest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Genre { get; set; }
        public string DateModified { get; set; }
        public int GroupingId { get; set; }
        public int TimesTaken { get; set; }
        public string Owner { get; set; }
        public string Upvotes { get; set; }
        public bool IsAdvanced { get; set; }
        public string TestFinishedDefaultMessage { get; set; }
        public string MessagesArrayAsSingleString { get; set; }
        public string AmountCorrectArrayAsSingleString { get; set; }
        public string AdditionalConditionsArrayAsSingleString { get; set; }
    }
}
